BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Issue] (
    [Id] INT NOT NULL IDENTITY(1,1),
    [Title] VARCHAR(255) NOT NULL,
    [Decription] NVARCHAR(1000) NOT NULL,
    [Status] NVARCHAR(1000) NOT NULL CONSTRAINT [Issue_Status_df] DEFAULT '0',
    [CreatedAt] DATETIME2 NOT NULL CONSTRAINT [Issue_CreatedAt_df] DEFAULT CURRENT_TIMESTAMP,
    [UpdatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [Issue_pkey] PRIMARY KEY CLUSTERED ([Id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
